tap "derailed/k9s"
tap "jandedobbeleer/oh-my-posh"
tap "olets/tap"
tap "xo/xo"
# Run your GitHub Actions locally
brew "act"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU binary tools for native development
brew "binutils"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Dart Language SDK, including the VM, dart2js, core libraries, and more
brew "dart-sdk"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# .NET Core
brew "dotnet"
# Generate documentation for several programming languages
brew "doxygen"
# Functional metaprogramming aware language built on Erlang VM
brew "elixir"
# GNU Emacs text editor
brew "emacs"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Disk usage analyzer with console interface written in Go
brew "gdu"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Language server for the Go language
brew "gopls"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Toolkit for creating graphical user interfaces
brew "gtk4"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Development kit for the Java programming language
brew "openjdk"
# Statically typed programming language for the JVM
brew "kotlin"
# Simple terminal UI for git commands
brew "lazygit"
# Powerful, lightweight programming language
brew "lua"
# Utility for directing compilation
brew "make"
# Cross platform, open source .NET development framework
brew "mono"
# Media player based on MPlayer and mplayer2
brew "mpv"
# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"
# Interactive cheatsheet tool for the command-line
brew "navi"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Programming language with focus on simplicity, performance and modern systems
brew "odin"
# Highly capable, feature-rich programming language
brew "perl"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Bundle a Python application and all its dependencies
brew "pyinstaller"
# Software environment for statistical computing
brew "r"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
brew "rustup"
# High-performance system programming language
brew "swift"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# CLI tool that moves files or folder to the trash
brew "trash"
# Language for application scale JavaScript development
brew "typescript"
# Ultra fast grep with query UI, fuzzy search, archive search, and more
brew "ugrep"
# Internet file retriever
brew "wget"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# Access X11 clipboards from the command-line
brew "xclip"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s"
# Prompt theme engine for any shell
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
# universal command-line SQL client interface
brew "xo/xo/usql", args: ["with-odbc"]
# Command-line interface for 1Password
cask "1password-cli"
# Automatic tiling window manager similar to xmonad
cask "amethyst"
# Distribution of the Python and R programming languages for scientific computing
cask "anaconda"
# Android SDK component
cask "android-platform-tools"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Tool to show live information about the batteries in various devices
cask "coconutbattery"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Create and run Linux containers using lightweight virtual machines
cask "container"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-fira-code-nerd-font"
# Desktop automation application
cask "hammerspoon"
# Chromium-based web browser
cask "helium-browser"
# Menu bar manager
cask "jordanbaird-ice"
# GPU-based terminal emulator
cask "kitty"
# Intercept, modify, replay, save HTTP/S traffic
cask "mitmproxy"
# App to write, plan, collaborate, and get organised
cask "notion"
# Generic satellite data processing software
cask "satdump"
# Media player based on MPlayer and mplayer2
cask "stolendata-mpv"
# Open-source code editor
cask "visual-studio-code"
vscode "asvetliakov.vscode-neovim"
vscode "catppuccin.catppuccin-vsc"
vscode "golang.go"
vscode "meezilla.json"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "vscodevim.vim"
vscode "zainchen.json"
go "github.com/tc-hib/go-winres"
go "github.com/rjhorniii/ical2org"
go "github.com/akavel/rsrc"
go "honnef.co/go/tools/cmd/staticcheck"
